CREATE DATABASE studentsdb;
USE studentsdb;
CREATE TABLE student (
id INT UNIQUE NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
document VARCHAR(11) NOT NULL UNIQUE,
registration VARCHAR(9) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
PRIMARY KEY(registration)
);