/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormUser: typeof import('./src/components/users/FormUser.vue')['default']
    ListUser: typeof import('./src/components/users/ListUser.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Login: typeof import('./src/components/auth/Login.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Success: typeof import('./src/components/Success.vue')['default']
  }
}
