/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ListUser: typeof import('./src/components/users/ListUser.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
