FROM node:18.16

RUN apt install bash

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node . .

RUN npm install

RUN npm run build

CMD [ "npm", "run", "start:dev" ]